/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Product;
/**
 *
 * @author aasikaleem
 */
public class CreateJpanel extends javax.swing.JPanel {
    Product product;

    /**
     * Creates new form CreateJpanel
     */
    public CreateJpanel(Product p) {
        initComponents();
        product = p;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        lblDiscription = new javax.swing.JLabel();
        lblAvailibility = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        fieldDescription = new javax.swing.JTextField();
        fieldAvialibility = new javax.swing.JTextField();
        fieldPrice = new javax.swing.JTextField();
        lblunitNumber = new javax.swing.JLabel();
        lblmanufactureAddress = new javax.swing.JLabel();
        lblstreetNumber = new javax.swing.JLabel();
        lblshippingAddress = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblzipCode = new javax.swing.JLabel();
        fieldStreetNumber = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldZipCode = new javax.swing.JTextField();
        fieldUnitNumber = new javax.swing.JTextField();
        lblShippingUnitNumber = new javax.swing.JLabel();
        lblShippingCity = new javax.swing.JLabel();
        lblShippingZipCode = new javax.swing.JLabel();
        lblShippingStreetNumber = new javax.swing.JLabel();
        fieldShippingStreetNumber = new javax.swing.JTextField();
        fieldShippingUnitNumber = new javax.swing.JTextField();
        fieldShippingCity = new javax.swing.JTextField();
        fieldShippingZipCode = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("Create a Prodcut");

        lblName.setText("  Name");

        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });

        lblDiscription.setText("Discription");

        lblAvailibility.setText("Availibility");

        lblPrice.setText("Price");

        fieldDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescriptionActionPerformed(evt);
            }
        });

        fieldAvialibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAvialibilityActionPerformed(evt);
            }
        });

        fieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPriceActionPerformed(evt);
            }
        });

        lblunitNumber.setText("Unit Number");

        lblmanufactureAddress.setText("Manufacture Address");

        lblstreetNumber.setText("Street Number");

        lblshippingAddress.setText("Shipping Address");

        lblCity.setText("City");

        lblzipCode.setText("Zip Code");

        fieldStreetNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStreetNumberActionPerformed(evt);
            }
        });

        lblShippingUnitNumber.setText("Unit Number");

        lblShippingCity.setText("City");

        lblShippingZipCode.setText("Zip Code");

        lblShippingStreetNumber.setText("Street Number");

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvailibility)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPrice)
                            .addComponent(fieldAvialibility))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiscription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldDescription))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(lblTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmanufactureAddress)
                            .addComponent(lblunitNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblzipCode)
                            .addComponent(lblCity))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldStreetNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(fieldUnitNumber)
                    .addComponent(fieldCity)
                    .addComponent(fieldZipCode))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblshippingAddress)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblShippingStreetNumber)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblShippingUnitNumber)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lblShippingZipCode)))
                                        .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldShippingUnitNumber)
                                    .addComponent(fieldShippingStreetNumber)
                                    .addComponent(fieldShippingZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblShippingCity)
                                        .addGap(42, 42, 42)
                                        .addComponent(fieldShippingCity, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSave))))
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblstreetNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblPrice)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnSave))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscription)
                    .addComponent(fieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailibility)
                    .addComponent(fieldAvialibility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmanufactureAddress)
                            .addComponent(lblshippingAddress))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblShippingStreetNumber)
                                .addComponent(fieldShippingStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblstreetNumber))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblunitNumber)
                            .addComponent(fieldUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShippingUnitNumber)
                            .addComponent(fieldShippingUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCity)
                            .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldShippingCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShippingCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblzipCode)
                            .addComponent(lblShippingZipCode))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldShippingZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescriptionActionPerformed

    private void fieldAvialibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAvialibilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAvialibilityActionPerformed

    private void fieldStreetNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStreetNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStreetNumberActionPerformed

    private void fieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPriceActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
//        Step 1 : Collect information from the field
            String name = fieldName.getText ();
            String description = fieldDescription.getText();
            String availibility = fieldAvialibility.getText();
            String price = fieldPrice.getText();
            
            String manuStreet = fieldStreetNumber.getText();
            String manuUnitNumber = fieldUnitNumber.getText();
            String manuCity = fieldCity.getText();
            String manuZipCode = fieldZipCode.getText();
            
            
            String shipStreet = fieldShippingStreetNumber.getText();
            String shipUnitNumber = fieldShippingUnitNumber.getText();
            String shipCity = fieldShippingCity.getText();
            String shipZipCode = fieldShippingZipCode.getText();
            
//            Step 2 Put information in the product

           product.setName(fieldName.getText());
           product.setDescription(fieldDescription.getText());
           product.setAvailNum(fieldAvialibility.getText());
//           the line below is done with outside help
           product.setPrice(Integer.parseInt(fieldPrice.getText())); 
           
           
            product.getManufacturerAddress().setStreetName(manuStreet);
            product.getManufacturerAddress().setUnitNum(manuUnitNumber);
            product.getManufacturerAddress().setCity(manuCity);
            product.getManufacturerAddress().setZipcode(manuZipCode);
    
    // Set shipping address
            product.getShippingAddress().setStreetName(shipStreet);  
            product.getShippingAddress().setUnitNum(shipUnitNumber);  
            product.getShippingAddress().setCity(shipCity);  
            product.getShippingAddress().setZipcode(shipZipCode);  

//Step 3: Set a little pop up message for save. 
//The next line i couldnt solve so took helpform AI

javax.swing.JOptionPane.showMessageDialog(this, "Successfully Saved!", "Success", javax.swing.JOptionPane.PLAIN_MESSAGE);
         

//Step 4: Clear all text field

        
            fieldName.setText("");
            fieldDescription.setText("");
            fieldAvialibility.setText("");
            fieldPrice.setText("");
            fieldStreetNumber.setText("");
            fieldUnitNumber.setText("");
            fieldCity.setText("");
            fieldZipCode.setText("");
            fieldShippingStreetNumber.setText("");
            fieldShippingUnitNumber.setText("");
            fieldShippingCity.setText("");
            fieldShippingZipCode.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAvialibility;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldShippingCity;
    private javax.swing.JTextField fieldShippingStreetNumber;
    private javax.swing.JTextField fieldShippingUnitNumber;
    private javax.swing.JTextField fieldShippingZipCode;
    private javax.swing.JTextField fieldStreetNumber;
    private javax.swing.JTextField fieldUnitNumber;
    private javax.swing.JTextField fieldZipCode;
    private javax.swing.JLabel lblAvailibility;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDiscription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblShippingCity;
    private javax.swing.JLabel lblShippingStreetNumber;
    private javax.swing.JLabel lblShippingUnitNumber;
    private javax.swing.JLabel lblShippingZipCode;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblmanufactureAddress;
    private javax.swing.JLabel lblshippingAddress;
    private javax.swing.JLabel lblstreetNumber;
    private javax.swing.JLabel lblunitNumber;
    private javax.swing.JLabel lblzipCode;
    // End of variables declaration//GEN-END:variables
}
